### ISSUE TITLE
Localization on navigation panel for TaxonomyPicker

### ISSUE THREAD

**Issue by dproietti412** [SharePoint/sp-dev-fx-controls-react#379] opened 2019-10-07 09:49 UTC
#### Category
[ ] Enhancement

[X] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.14.0 ]

#### Expected / Desired Behavior / Question
Localization of all controls used by the component.

#### Observed Behavior
The buttons "Save" and "Cancel" are showed in english Language also if the component use another localization.
In the code file "TaxonomyPicker.js" (TaxonomyPicker.prototype.render) the text is "hardcoded" in the file instead of get the reference from resource file.

#### Steps to Reproduce
Localize the component in a Language different from english and open the navigation panel

Thanks!

**Comment by AJIXuMuK** [comment] 2019-10-09 16:40
Hey @dproietti412,
This is a duplicate of #361 
It will be fixed in the next drop. Thanks to @robert-lindstrom

**Closed by AJIXuMuK** 2019-10-09 16:40 UTC
Labels: status:fixed-next-drop
