### ISSUE TITLE
Sort fails if column contains underscore

### ISSUE THREAD

**Issue by robpearmain** [SharePoint/sp-dev-fx-controls-react#12] opened 2017-12-05 09:58 UTC
[X ] Bug

Please specify what version of the library you are using: [  "@pnp/spfx-controls-react": "1.0.0-beta.8"       ]

#### Expected / Desired Behavior / Question

In Viewfields

_viewFields: IViewField[] some fields have underscores, e.g.

{
      name: "requester_name",
      displayName: "Requester Name",
      minWidth: 100,
      sorting: true
    }

Sorting should allow the column to be sorted

#### Observed Behavior

We get an error in the console

1512467795079][OtherGlobalError.window.onerro] TypeError: Cannot read property 'name' of undefined
TraceLogger._writeToConsole @ sp-loader-assembly_en-us.js:20165
TraceLogger._log @ sp-loader-assembly_en-us.js:20148
TraceLogger.logError @ sp-loader-assembly_en-us.js:20107
SPGlobalErrorHandler.basicTracingHandler @ SPGlobalErrorHandler.js:15
ReactErrorUtils.invokeGuardedCallback @ react-dom.js:9017
executeDispatch @ react-dom.js:3006
executeDispatchesInOrder @ react-dom.js:3029
executeDispatchesAndRelease @ react-dom.js:2431
executeDispatchesAndReleaseTopLevel @ react-dom.js:2442
forEachAccumulated @ react-dom.js:15423
processEventQueue @ react-dom.js:2645
runEventQueueInBatch @ react-dom.js:9041
handleTopLevel @ react-dom.js:9052
handleTopLevelImpl @ react-dom.js:9129
perform @ react-dom.js:14724
batchedUpdates @ react-dom.js:8805
batchedUpdates @ react-dom.js:12852
dispatchEvent @ react-dom.js:9204

Followed by

ListView.tsx:279 Uncaught TypeError: Cannot read property 'name' of undefined
    at ListView.tsx:279
    at baseFindIndex (sp-loader-assembly_en-us.js:13012)
    at r.findIndex (sp-loader-assembly_en-us.js:17205)
    at ListView._columnClick (ListView.tsx:279)
    at DetailsHeader._onColumnClick (DetailsHeader.tsx:581)
    at Object.ReactErrorUtils.invokeGuardedCallback (react-dom.js:9017)
    at executeDispatch (react-dom.js:3006)
    at Object.executeDispatchesInOrder (react-dom.js:3029)
    at executeDispatchesAndRelease (react-dom.js:2431)
    at executeDispatchesAndReleaseTopLevel (react-dom.js:2442)

#### Steps to Reproduce

In your JSON feed have a column with an underscore

e.g. 

requester_name

**Comment by estruyf** [comment] 2017-12-06 10:18
Thanks for reporting this, will take a look at it.

**Comment by estruyf** [comment] 2017-12-07 14:08
@robpearmain can't reproduce this in my environments. Can you give more details in which browser(s) this error occurs?

**Comment by estruyf** [comment] 2018-03-02 13:46
Closing the issue. Feel free to reopen it if you have more information or if the problem still occurs.

**Closed by estruyf** 2018-03-02 13:46 UTC
Labels: bug
