### ISSUE TITLE
TaxonomyPicker - suggestions are not working. Error

### ISSUE THREAD

**Issue by Matej4386** [SharePoint/sp-dev-fx-controls-react#425] opened 2019-12-05 10:28 UTC
#### Category
[ ] Enhancement

[X ] Bug

[ ] Question

#### Version

Please specify what version of the library you are using: [ 1.15.0 ]

#### Expected / Desired Behavior / Question
TermSetPicker - suggestions should list available suggestions under input element.
TermSet and TermSetItems are correctlly displayed in Panel. I can select, ...

#### Observed Behavior
After typing letters there is error in console and suggestions are not displayed.
```
Error: Uncaught (in promise) TypeError: Cannot read property '_ObjectType_' of null
    at SPTermStorePickerService.js:129
    at Array.filter (<anonymous>)
    at SPTermStorePickerService.js:129
```

#### Steps to Reproduce
<TaxonomyPicker 
                  allowMultipleSelections={false}
                  termsetNameOrID="9e9e3b0b-f9b6-4814-9dc9-5639aed4ea64" //this is ID of my TermSet, strange is that this works only for ID, not for Term Set Name
                  panelTitle="Choose"
                  label="Taxonomy"
                  context={this.props.context}
                  onChange={this.onTaxPickerChange}
                  isTermSetSelectable={false} 
                />

**Comment by AJIXuMuK** [comment] 2019-12-05 17:40
Hi @Matej4386,
I've tested your code and it works correctly.
could you please check that you use correct term set id and testing things in SharePoint, not a local workbech?
![tax-picker](https://user-images.githubusercontent.com/17036219/70259488-22a97500-1743-11ea-9dec-3ce810ef8eaf.png)

**Comment by Matej4386** [comment] 2019-12-06 06:29
Hi @AJIXuMuK,
thanks for reply. I am not using local workbench.

I think i use correct TermSet ID:
![image](https://user-images.githubusercontent.com/58258968/70301022-7aa2b300-17f9-11ea-8b5d-1589db74e8d6.png)

After click on button next to the input, Panel is working, i can select terms, everything works:
![image](https://user-images.githubusercontent.com/58258968/70301118-c81f2000-17f9-11ea-845b-888dd37eb8d0.png)

But when i start typing in input, suggestions are not working:
![image](https://user-images.githubusercontent.com/58258968/70301197-074d7100-17fa-11ea-82ec-6cdf9808e126.png)

**Comment by AJIXuMuK** [comment] 2019-12-06 16:47
Are you on-prem or online?

Could you please investigate Network tab? There should be request to `ProcessQuery.svc`. And in the response you should see your term store objects.
Could you share it with me or at least investigate what object in there miss `__ObjectType__` property?

**Comment by Matej4386** [comment] 2019-12-06 18:55
@AJIXuMuK ,
I am on-prem.
Och, i am at home and will have vacation for whole week ... I can share it on monday 16.12.
I looked at it few days ago, compared it to the query in panel (which is working) and there was difference - working query (i thing "get all") had in response all terms, but filtered query had null.

**Comment by Matej4386** [comment] 2019-12-16 06:26
@AJIXuMuK ,
finally at work ... Here is response:
[
{
"SchemaVersion":"15.0.0.0","LibraryVersion":"16.0.10351.20000","ErrorInfo":null,"TraceCorrelationId":"c8f8219f-e457-408b-7c4e-a43af68b26ab"
},2,{
"IsNull":false
},3,{
"_ObjectIdentity_":"c8f8219f-e457-408b-7c4e-a43af68b26ab|fec14c62-7c3b-481b-851b-c80d7802b224:ss:"
},5,{
"IsNull":true
},6,null,7,null
]

Query for Panel:
[
{
"SchemaVersion":"15.0.0.0","LibraryVersion":"16.0.10351.20000","ErrorInfo":null,"TraceCorrelationId":"e7f8219f-2419-408b-7c4e-a6a9b889a46d"
},1,{
"IsNull":false
},2,{
"_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:ss:"
},4,{
"IsNull":false
},5,{
"_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:st:2lcTDuEg90avCv6W6CkbwA=="
},7,{
"IsNull":false
},8,{
"_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:se:2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1Opk"
},10,{
"IsNull":false
},11,{
"_ObjectType_":"SP.Taxonomy.TermSet","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:se:2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1Opk","CreatedDate":"\/Date(1573720149003)\/","Id":"\/Guid(9e9e3b0b-f9b6-4814-9dc9-5639aed4ea64)\/","LastModifiedDate":"\/Date(1573720149003)\/","Name":"CEZ_TypZmluvy","CustomProperties":{

},"CustomSortOrder":null,"IsAvailableForTagging":true,"Owner":"blblbaaaa","Contact":"","Description":"","IsOpenForTermCreation":false,"Names":{
"1033":"CEZ_TypZmluvy"
},"Stakeholders":[

]
},12,{
"_ObjectType_":"SP.Taxonomy.TermCollection","_Child_Items_":[
{
"_ObjectType_":"SP.Taxonomy.Term","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:te:2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1Opk1dypGhbPVkeyLxKg7cgkWw==","IsRoot":true,"Labels":{
"_ObjectType_":"SP.Taxonomy.LabelCollection","_Child_Items_":[
{
"_ObjectType_":"SP.Taxonomy.Label","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:la:;1033;Biela;2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1Opk1dypGhbPVkeyLxKg7cgkWw==","IsDefaultForLanguage":true,"Language":1033,"Value":"Biela"
}
]
},"TermsCount":0,"CustomSortOrder":null,"Id":"\/Guid(1aa9dcd5-cf16-4756-b22f-12a0edc8245b)\/","Name":"Biela","PathOfTerm":"Biela","Parent":null,"LocalCustomProperties":{

},"IsDeprecated":false,"IsAvailableForTagging":true
},{
"_ObjectType_":"SP.Taxonomy.Term","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:te:2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1OpkXS3hiucm4kqFg\u002fBvD7U8FA==","IsRoot":true,"Labels":{
"_ObjectType_":"SP.Taxonomy.LabelCollection","_Child_Items_":[
{
"_ObjectType_":"SP.Taxonomy.Label","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:la:;1033;Cierna;2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1OpkXS3hiucm4kqFg\u002fBvD7U8FA==","IsDefaultForLanguage":true,"Language":1033,"Value":"Cierna"
}
]
},"TermsCount":0,"CustomSortOrder":null,"Id":"\/Guid(8ae12d5d-26e7-4ae2-8583-f06f0fb53c14)\/","Name":"Cierna","PathOfTerm":"Cierna","Parent":null,"LocalCustomProperties":{

},"IsDeprecated":false,"IsAvailableForTagging":true
},{
"_ObjectType_":"SP.Taxonomy.Term","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:te:2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1OpktJ6cVqWwqEOXYNcsc9KMiw==","IsRoot":true,"Labels":{
"_ObjectType_":"SP.Taxonomy.LabelCollection","_Child_Items_":[
{
"_ObjectType_":"SP.Taxonomy.Label","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:la:;1033;Fialova;2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1OpktJ6cVqWwqEOXYNcsc9KMiw==","IsDefaultForLanguage":true,"Language":1033,"Value":"Fialova"
}
]
},"TermsCount":0,"CustomSortOrder":null,"Id":"\/Guid(569c9eb4-b0a5-43a8-9760-d72c73d28c8b)\/","Name":"Fialova","PathOfTerm":"Fialova","Parent":null,"LocalCustomProperties":{

},"IsDeprecated":false,"IsAvailableForTagging":true
},{
"_ObjectType_":"SP.Taxonomy.Term","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:te:2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1OpkhoeAP4WfRUGXnk10656ruw==","IsRoot":true,"Labels":{
"_ObjectType_":"SP.Taxonomy.LabelCollection","_Child_Items_":[
{
"_ObjectType_":"SP.Taxonomy.Label","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:la:;1033;Mala;2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1OpkhoeAP4WfRUGXnk10656ruw==","IsDefaultForLanguage":true,"Language":1033,"Value":"Mala"
}
]
},"TermsCount":0,"CustomSortOrder":null,"Id":"\/Guid(3f808786-9f85-4145-979e-4d74eb9eabbb)\/","Name":"Mala","PathOfTerm":"Mala","Parent":null,"LocalCustomProperties":{

},"IsDeprecated":false,"IsAvailableForTagging":true
},{
"_ObjectType_":"SP.Taxonomy.Term","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:te:2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1OpkBmNhYedip0OlAAisPAYMEQ==","IsRoot":true,"Labels":{
"_ObjectType_":"SP.Taxonomy.LabelCollection","_Child_Items_":[
{
"_ObjectType_":"SP.Taxonomy.Label","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:la:;1033;Modra;2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1OpkBmNhYedip0OlAAisPAYMEQ==","IsDefaultForLanguage":true,"Language":1033,"Value":"Modra"
}
]
},"TermsCount":0,"CustomSortOrder":null,"Id":"\/Guid(61616306-62e7-43a7-a500-08ac3c060c11)\/","Name":"Modra","PathOfTerm":"Modra","Parent":null,"LocalCustomProperties":{

},"IsDeprecated":false,"IsAvailableForTagging":true
},{
"_ObjectType_":"SP.Taxonomy.Term","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:te:2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1OpkIR\u002fO2JJRCECLpzBvn1dH9A==","IsRoot":true,"Labels":{
"_ObjectType_":"SP.Taxonomy.LabelCollection","_Child_Items_":[
{
"_ObjectType_":"SP.Taxonomy.Label","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:la:;1033;Ruzova;2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1OpkIR\u002fO2JJRCECLpzBvn1dH9A==","IsDefaultForLanguage":true,"Language":1033,"Value":"Ruzova"
}
]
},"TermsCount":0,"CustomSortOrder":null,"Id":"\/Guid(d8ce1f21-5192-4008-8ba7-306f9f5747f4)\/","Name":"Ruzova","PathOfTerm":"Ruzova","Parent":null,"LocalCustomProperties":{

},"IsDeprecated":false,"IsAvailableForTagging":true
},{
"_ObjectType_":"SP.Taxonomy.Term","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:te:2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1Opk7F4FtrZFI0GuwRfcHuiaug==","IsRoot":true,"Labels":{
"_ObjectType_":"SP.Taxonomy.LabelCollection","_Child_Items_":[
{
"_ObjectType_":"SP.Taxonomy.Label","_ObjectIdentity_":"e7f8219f-2419-408b-7c4e-a6a9b889a46d|fec14c62-7c3b-481b-851b-c80d7802b224:la:;1033;Velka;2lcTDuEg90avCv6W6CkbwE5cBNvHQCZOiQ3IfdgAGboLO56etvkUSJ3JVjmu1Opk7F4FtrZFI0GuwRfcHuiaug==","IsDefaultForLanguage":true,"Language":1033,"Value":"Velka"
}
]
},"TermsCount":0,"CustomSortOrder":null,"Id":"\/Guid(b6055eec-45b6-4123-aec1-17dc1ee89aba)\/","Name":"Velka","PathOfTerm":"Velka","Parent":null,"LocalCustomProperties":{

},"IsDeprecated":false,"IsAvailableForTagging":true
}
]
}
]

**Comment by AJIXuMuK** [comment] 2019-12-17 03:11
Hey @Matej4386,

Could you please install the beta version and see if it's fixed in there? I committed a potential fix but I can't reproduce the issue so can't tell for sure if it works :)

Here is a link on how to install the beta version: [https://sharepoint.github.io/sp-dev-fx-controls-react/beta/](https://sharepoint.github.io/sp-dev-fx-controls-react/beta/)

**Comment by Matej4386** [comment] 2019-12-17 07:40
Hello @AJIXuMuK,
I have installed beta version - @pnp/spfx-controls-react@1.17.0-beta.28a445d ,
but it did not work ... same error, same result.

I have looked at the code in SPTermStorePickerService.js, in SPTermStorePickerService.prototype.getTermStores there was a call with data:
....
<ObjectPaths>
		<StaticMethod Id="1" Name="GetTaxonomySession" TypeId="{981cbc68-9edc-4f8d-872f-71146fcbb84f}" />
		<Method Id="4" ParentId="1" Name="GetDefaultSiteCollectionTermStore" />
	</ObjectPaths>
...
This call returned null parameter.
I changed it to:
<ObjectPaths><StaticMethod Id="0" Name="GetTaxonomySession" TypeId="{981cbc68-9edc-4f8d-872f-71146fcbb84f}" /><Method Id="3" ParentId="0" Name="GetDefaultKeywordsTermStore"  /><Method Id="6" ParentId="3" Name="GetTermSet"><Parameters><Parameter Type="Guid">9e9e3b0b-f9b6-4814-9dc9-5639aed4ea64</Parameter></Parameters></Method></ObjectPaths>

And it worked !!!!
![image](https://user-images.githubusercontent.com/58258968/70974145-61c2b900-20a7-11ea-9dc8-009a10130642.png)

So i figured it out that there is a problem with "getdefaultsitecollectiontermstore" call -> google -> result: central administration of my dev SharePoint site - one checkbox based on this article https://mohitvash.wordpress.com/2014/02/18/sharepoint-defaultsitecollectiontermstore-is-null/
And now it works as expected (with "getdefaultsitecollectiontermstore" call) .
Thank you for your time, there was problem on my environment.

Just wanted to share this ;-)

**Closed** 2019-12-17 07:43 UTC
Labels: status:tracked, status:working-on-it, type:bug

**Comment by Gnanavelvengat** [comment] 2022-09-01 21:00
Taxonomy not showing items
