### ISSUE TITLE
IconPicker: impossible to filter icons

### ISSUE THREAD

**Issue by SemionKovaliov** [SharePoint/sp-dev-fx-controls-react#544] opened 2020-04-24 15:06 UTC
#### Category
[ ] Enhancement

[x] Bug

[ ] Question

#### Version

1.17.0

#### Expected / Desired Behavior / Question
Filter icon when typing icon name in textfield

#### Observed Behavior
nothing happend

#### Steps to Reproduce
1. open icons panel
2. type anything in textfield

#### Submission Guidelines
Console output shows this:

IconPicker.js:52 Uncaught TypeError: Cannot read property 'length' of undefined
    at IconPicker._this.onChange (IconPicker.js:52)
    at invokeFunc (lodash.js:10350)
    at trailingEdge (lodash.js:10397)
    at timerExpired (lodash.js:10385)

this happens in onChange function of this textfield

Thanks!

**Comment by AJIXuMuK** [comment] 2020-04-28 05:03
Hi @SemionKovaliov!
Thank you for reporting the bug. This is a duplicate of #512 
The fix has been merged and will be added to the next release.
You can also test it right away in beta version.

**Closed by AJIXuMuK** 2020-04-28 05:03 UTC
Labels: status:duplicate
